# meta file
---
galaxy_info:
  author: oefenweb
  role_name: fail2ban
  company: Oefenweb.nl B.V.
  description: Set up fail2ban in Debian-like systems
  license: MIT
  min_ansible_version: 2.10.0
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy
    - name: Debian
      versions:
        - buster
        - bullseye
        - bookworm
  galaxy_tags:
    - system
    - networking
dependencies: []
