- hosts: qnap
  become: true
  gather_facts: true
  vars_files:
    - ./group_vars/vars.yml

  environment:
    PATH: "/opt/bin:/opt/sbin:/usr/bin:/usr/sbin:{{ ansible_env.PATH }}"

  tasks:
    - name: Update cache and install nano
      community.general.opkg:
        name: nano
        state: present
        update_cache: true

    - name: Install pip
      community.general.opkg:
        name: python3-pip
        state: present

    - name: Install requests
      ansible.builtin.pip:
        name: requests

    - name: Get Plex container info
      community.general.docker_container_info:
        name: plex
      register: result

    - name: Does it exist
      debug:
        msg: "The container {{ 'exists' if result.exists else 'does not exist' }}"

    - name: Print information about container
      debug:
        var: result.container.State.Running
      when: result.exists
