# tasks file
---
- name: RESCUE - Copy zfs compile script
  ansible.builtin.copy:
    src: hetzner-rescue-zfs-compile-script.sh
    dest: /tmp/hetzner-rescue-zfs-compile-script.sh
    owner: root
    group: root
    mode: "0755"

- name: RESCUE - Run zfs compile script
  ansible.builtin.shell: /tmp/hetzner-rescue-zfs-compile-script.sh
  args:
    chdir: /tmp
