# tasks file
---
- name: RESCUE - Copy debian 12 zfs setup script
  ansible.builtin.copy:
    src: deb12bootzfs.sh
    dest: /tmp/deb12bootzfs.sh
    owner: root
    group: root
    mode: "0755"

- name: RESCUE - Run debian 12 zfs setup script
  ansible.builtin.shell: /tmp/deb12bootzfs.sh
  args:
    chdir: /tmp
