# tasks file
---
- name: RESCUE - Copy debian 12 zfs script config
  ansible.builtin.template:
    src: config.sh.j2
    dest: /tmp/config.sh
    owner: root
    group: root
    mode: "0755"

- name: RESCUE - Copy debian 12 zfs script
  ansible.builtin.copy:
    src: "{{item}}"
    dest: /tmp
    owner: root
    group: root
    mode: "0755"
  loop:
    - config.sh
    - 01-deb12bootzfs-disk-prep.sh
    - 02-deb12bootzfs-system-locale.sh
    - 03-deb12bootzfs-kernel-zfs.sh
    - 04-deb12bootzfs-network-apps-finish.sh

- name: RESCUE - Run debian 12 zfs disk prep script
  ansible.builtin.shell: /tmp/01-deb12bootzfs-disk-prep.sh
  args:
    chdir: /tmp

- name: RESCUE - Run debian 12 system and locale script
  ansible.builtin.shell: /tmp/02-deb12bootzfs-system-locale.sh
  args:
    chdir: /tmp

- name: RESCUE - Run debian 12 kernel and zfs script
  ansible.builtin.shell: /tmp/03-deb12bootzfs-kernel-zfs.sh
  args:
    chdir: /tmp

- name: RESCUE - Run debian 12 kernel network apps and finish script
  ansible.builtin.shell: /tmp/04-deb12bootzfs-network-apps-finish.sh
  args:
    chdir: /tmp
