# tasks file
---
# Reboot server
# Take snapshots of the pools

- name: Reboot RESCUE and wait for it to restart as Debian 12 on ZFS
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 2
    post_reboot_delay: 30
    test_command: whoami
