# tasks file
---
# Reboot server
# Take snapshots of the pools

- name: RESCUE - Reboot and wait for it to restart as Debian 12 on ZFS
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 2
    post_reboot_delay: 30
    test_command: whoami

- name: Gather server information for hosts
  ansible.builtin.setup:

- name: Add fqdn to hosts file
  ansible.builtin.lineinfile:
    path: /etc/hosts
    search_string: "{{ ansible_default_ipv4.address }}"
    line: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }} {{ inventory_hostname_short }}"

# Install an NTP service to synchronize time
- name: DEB 12 - Ensure systemd-timesyncd is installed
  package:
    name: chrony
    state: present

- name: DEB12 - Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: yes

- name: Create a snapshot of rpool
  community.general.zfs:
    name: rpool/ROOT/debian@install
    state: present

- name: Create a snapshot of bpool
  community.general.zfs:
    name: bpool/BOOT/debian@install
    state: present
