---
- ansible.builtin.include_tasks: 00_hetzner_force_to_rescue_mode.yml
  # when: hetzner_pve_autorescue

- ansible.builtin.include_tasks: 01_rescue_prepare_server.yml

- ansible.builtin.include_tasks: 02_rescue_compile_zfs.yml

- ansible.builtin.include_tasks: 03_rescue_zfs_create.yml

- ansible.builtin.include_tasks: 05_reboot_snapshot.yml
