# vars file
---
fail2ban_dependencies:
  - fail2ban
  - "{{ (fail2ban_backend == 'systemd') | ternary('python' + (ansible_python_version is version('3', '>=') | ternary('3', '')) + '-systemd', '') }}"
