---
# - name: Rebooting and unlock
#   ansible.legacy.reboot:
#     post_reboot_delay: 20
#     test_command: "echo -ne {{ hetzner_pve_luks_pass }} > /test.txt"

# - name: Wait for system coming up after unlock
#   ansible.legacy.wait_for:
#     port: 22
#     host: "{{ inventory_hostname }}"
#     delay: 20
#   delegate_to: localhost

# - name: HETZNER - Reset SERVER
#   community.hrobot.reset:
#     hetzner_user: "{{ hetzner_pve_hetzner_api_user }}"
#     hetzner_password: "{{ hetzner_pve_hetzner_api_pass }}"
#     server_number: "{{ ENV_INVENTORY_SRV_NO }}"
#     reset_type: hardware
#   delegate_to: localhost

# - name: LOCAL - Pause for 2 mins for the reboot to kick in
#   pause: seconds=120

# - name: HETZNER - Waiting for server to come back
#   local_action:
#     module: wait_for
#       host={{ inventory_hostname }}
#       port=22
#       delay=1
#       timeout=90

- name: Reboot host and wait for it to restart
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 2
    post_reboot_delay: 30
    test_command: whoami
