---
# tasks file for zfs_filesystem
# Only run these if asked to create the pool
- name: Install ZFS pool if required
  when: zfs_filesystem_install_pool
  block:
    - name: Check ZFS pool existence
      ansible.builtin.command: zpool list -Ho name {{ zfs_filesystem_pool_name }}
      register: result_pool_list
      ignore_errors: true
      changed_when: false

    - name: Create ZFS pool
      ansible.builtin.command: >-
        zpool create
        {{ zfs_filesystem_pool_options | join(' ') }}
        {{ zfs_filesystem_pool_name }}
        {{ zfs_filesystem_pool_mode if zfs_filesystem_pool_mode else '' }}
        {{ zfs_filesystem_pool_devices | join(' ') }}
      when:
        - zfs_filesystem_pool_state | default('present') == 'present'
        - result_pool_list.rc == 1
      changed_when: my_output.rc != 0

    - name: Import created pool
      ansible.builtin.command: >-
        zpool import {{ zfs_filesystem_pool_name }}
      when:
        - zfs_filesystem_pool_state | default('present') == 'present'
        - result_pool_list.rc == 1
      changed_when: my_output.rc != 0

- name: Create ZFS file systems
  community.general.zfs:
    name: "{{ zfs_filesystem_pool_name }}/{{ item }}"
    state: present
  with_items: "{{ zfs_filesystem_filesystems }}"
  tags: storage
