---
# tasks file for zfs_filesystem
# Only run these if asked to create the pool
- name: Install ZFS pool if required
  when: zfs_filesystem_install_pool
  block:
    - name: Check ZFS pool existence
      ansible.builtin.command: zpool list -Ho name {{ zfs_filesystem_pool_name }}
      register: result_pool_list
      ignore_errors: true
      changed_when: false

    # NOW CHECK IF POOL WITH SAME NAME WAITING FOR IMPORT
    # NOT CLEAR HOW TO DO THIS, SO SCRIPT CURRENTLY CRASHES
    # OUT. PERHAPS A VARIABLE FLAG TO FORCE EXISTING POOL
    # OVERWRITE?

    - name: Create ZFS pool
      ansible.builtin.command: >-
        zpool create
        {{ zfs_filesystem_pool_options | join(' ') }}
        {{ zfs_filesystem_pool_name }}
        {{ zfs_filesystem_pool_mode if zfs_filesystem_pool_mode else '' }}
        {{ zfs_filesystem_pool_devices | join(' ') }}
      when:
        - zfs_filesystem_pool_state | default('present') == 'present'
        - result_pool_list.rc == 1

    - name: Import created pool
      ansible.builtin.command: >-
        zpool import {{ zfs_filesystem_pool_name }}
      when:
        - zfs_filesystem_pool_state | default('present') == 'present'
        - result_pool_list.rc == 1

- name: Create ZFS file systems
  community.general.zfs:
    name: "{{ zfs_filesystem_pool_name }}/{{ item.name }}"
    extra_zfs_properties:
      mountpoint: "{{ item.mountpath }}"
    state: present
  with_items: "{{ zfs_filesystem_filesystems }}"
  tags: storage
