---
- name: "Wipe and set up minimal Debian 12 bookworm on Hetzer server with ZFS filesystem"
  hosts: vmhost
  user: root
  gather_facts: false

  roles:
    #  - role: "hetzner_deb12_zfs"
    - role: "fail2ban"
      vars:
        fail2ban_backend: systemd
        fail2ban_logtarget: systemd
        fail2ban_bantime: 1h
        fail2ban_findtime: 2d
        fail2ban_filterd_path: ~/ansible/roles/fail2ban/templates/etc/fail2ban/filter.d/
        fail2ban_jaild_path: ~/ansible/roles/fail2ban/templates/etc/fail2ban/jail.d/
        fail2ban_ignoreips:
          - 127.0.0.1/8
          - ::1
          - 95.141.18.213 # G Network IP address
