- name: View Linode Instance Status
  hosts: localhost
  vars_files:
    - ~/ansible/inventory/group_vars/linode/01 vars.yml
    - ~/ansible/inventory/group_vars/linode/10 vault.yml

  tasks:
    - name: View Linode instance status
      linode.cloud.instance_info:
        api_token: "{{ linode_api_token }}"
        label: "linode8175244"
      register: info

    - debug:
        msg:
          - "Label:  {{ info.instance.label }}"
          - "CPUs:   {{ info.instance.specs.vcpus }}"
          - "Mem:    {{ info.instance.specs.memory }}"
          - "Disk:   {{ info.instance.specs.disk }}"
          - "IP:     {{ info.networking.ipv4.private[0].address}}"
          - "OS:     {{ info.instance.image }}"
          - "Status: {{ info.instance.status }}"
