---
- name: "Wipe and set up minimal Debian 12 bookworm on Hetzer server with ZFS filesystem"
  hosts: vmhost
  user: root
  gather_facts: false
  vars_files:
    - ~/ansible/roles/hetzner_deb12_zfs/defaults/main.yml
    - ~/ansible/roles/hetzner_deb12_zfs/vars/main.yml
  tasks:
    - name: RESCUE - Copy debian 12 zfs script config
      ansible.builtin.template:
        src: ~/ansible/roles/hetzner_deb12_zfs/templates/config.sh.j2
        dest: ~/ansible/config.sh
      delegate_to: localhost
