---
- name: "Temporary playbook for testing lae.proxmox role"
  hosts: pve01
  user: root
  gather_facts: true
  # vars_files:
  #   - ~/ansible/roles/hetzner_deb12_zfs/defaults/main.yml
  tasks:
    - name: Test lae.proxmox
      ansible.builtin.include_role:
        name: lae.proxmox
      vars:
        - pve_group: pve01
        - pve_reboot_on_kernel_update: true
